name: annotations
channels:
  - defaults
dependencies:
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - libcxx=10.0.0
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.0.1
  - python=3.8.8
  - readline=8.1
  - sqlite=3.35.4
  - tk=8.6.10
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - bio==0.4.1
    - biopython==1.78
    - chardet==4.0.0
    - gemmi==0.4.5
    - idna==2.10
    - lxml==4.6.3
    - numpy==1.19.5
    - requests==2.25.1
    - setuptools==42.0.2
    - urllib3==1.26.3
    - wheel==0.33.6