on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deployment:
    if: github.event.pull_request.merged == true
    runs-on: 
      - self-hosted
    steps:
      - name: Pull repository
        run:
          ssh ${{ secrets.SRUN_SERVER }} "git -C ${{ secrets.DEPLOY_PATH }} pull"
      - name: Send e-mail
        run:
          echo "The AddedAnnotations repository was pulled and moved to production." | s-nail -s "[emdb-emicss] addedAnnotations has updated" pdb_em@ebi.ac.uk
